from .yeaseq_config import Yeast


_VERSION = (0, 3, 9)

__version__ = '.'.join(map(str, _VERSION))

__author__ = 'Lou, R.'
__email__ = 'lourh@shanghaitech.edu.cn'
__repository__ = 'https://github.com/Sugiyama-Lab/Yeaseq'

__short_description__ = 'Sequence viewer for yeast'


__description__ = '''
For seq data extraction from biomart or entrez
'''

__UnderChange__ = '''

-----------------------------------------------------
Defined in 2021-01-14

Done 1. Font family to: Helvetica or Arial
Done 2. Font size: more large
Done 3. Widgets positions of Seq frame:
    * Infomation as upper
    * Type at lower left
    * Display at lower right
Done 4. Stable gene ID -> Ensembl ID
Done 5. Remove comma for numbers over 1000: 1,000 -> 1000

'''

__TODO__ = '''

-----------------------------------------------------
Defined in 2020-02-02

Done 1. 可以搜索 CDS 的 GenBank ID，即 XP_... or NP_...
Done 2. First col (Search information) 不确定宽度是否会因为某些 information 过宽
3. Gauge when search and download
'''

AboutMessage = '''
Sequence viewer for four fission yeasts: \n    {yeast_list}\n
Version: {ver}

For more information, please visit:
    {repo}

Yeaseq is under a general MIT license

Used python built-in packages are:
    urllib, gzip, os, sys, json, re, xml, platform, shutil, io, setuptools

Used third-party python packages are:
    requests, wxpython
    
Executable file is generated by PyInstaller for Windows, MacOS, and Linux'''.format(
            yeast_list=',\n    '.join(Yeast.YeastList),
            repo=__repository__,
            ver=__version__
)

HelpMessage = '''
Search Ensembl ID:
    Ensembl ID used here is also called stable gene ID, which is usually the systematic name of gene
    e.g. SPBC11B10.09 for pombe
    e.g. SJAG_01836 for japonicus

Search Entrez gene ID:
    Entrez ID indicates the unique digital gene ID used in NCBI Entrez database
    e.g. 2539869
    
    If offline search is open, RNA and protein Genbank ID are also supported here
    e.g. NM_001356226.1 for RNA
    e.g. NP_001342995.1 for protein

    New in version 0.3.2:
    In offline mode, gene name and some aliases are also valid now
    e.g. cdc2 for SPBC11B10.09 and the aliases cdk1, swo2, tws1 are of the same effect
'''.format(
    repo=__repository__
)

# OrthoGeneInfo = '''\
# Note: this orthologous gene finder tool is based on the orthologous information\
#  provided by Nicholas Rhind et.al. in their comparative study for fission yeast gonome. \
# Please cite \
# Rhind, N. et al. Science 332, 930–6 (2011).
# '''

OrthoGeneInfo = '''\
Note: this ortholog finder uses the information provided by Rhind et.al. [PMID: 21511999]
'''

BLASTMessage = '''
https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=DeveloperInfo

We will move searches of users who submit more than 100 searches in a 24 hour period to a slower queue, or, in extreme cases, will block the requests. To avoid problems, API users should comply with the following guidelines:

    Do not contact the server more often than once every 10 seconds.
    Do not poll for any single RID more often than once a minute.
    Use the URL parameter email and tool, so that the NCBI can contact you if there is a problem.
    Run scripts weekends or between 9 pm and 5 am Eastern time on weekdays if more than 50 searches will be submitted.

BLAST often runs more efficiently if multiple queries are sent as one search rather than if each query is sent as an individual search. This is especially true for blastn, megablast, and tblastn. If your queries are short (less than a few hundred bases) we suggest you merge them into one search of up to 1,000 bases
'''
